# Generated by Django 3.1.7 on 2021-03-04 07:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(4, ' must be greater than 4 character')])),
                ('username', models.CharField(blank=True, max_length=60, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(4, ' must be greater than 4 character')])),
                ('phone_number', models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,10}$')])),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(4, ' must be greater than 4 character')])),
                ('price', models.DecimalField(decimal_places=0, max_digits=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.people')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, validators=[django.core.validators.MinLengthValidator(3, ' must be greater than 3 character')])),
                ('people', models.ManyToManyField(to='api.People')),
                ('transaction', models.ManyToManyField(to='api.Transaction')),
            ],
        ),
    ]
