# Generated by Django 3.1.7 on 2021-03-04 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='people',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '0912*******'. Up to 11 digits allowed.", regex='^\\+?1?\\d{9,11}$')]),
        ),
    ]
