# Generated by Django 3.1.7 on 2021-03-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='persons',
            field=models.ManyToManyField(related_name='action_persons', to='panel.People'),
        ),
    ]
